# Generated by Django 4.2.7 on 2023-12-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mfluser',
            table='users_mfluser',
        ),
    ]
