# Generated by Django 4.2.7 on 2023-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='number_of_inpatient_beds',
        ),
    ]
