# Generated by Django 4.2.7 on 2023-12-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_facility_number_of_inpatient_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='number_of_inpatient_beds',
            field=models.PositiveIntegerField(default=0, help_text='The number of General In-patient beds that a facility has e.g 0'),
        ),
    ]
