# Generated by Django 4.2.7 on 2023-12-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_number_of_inpatient_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='approvalrejection_date',
        ),
    ]
