# Generated by Django 4.2.7 on 2023-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_remove_facility_approvalrejection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='approvalrejection_date',
            field=models.DateTimeField(blank=True, help_text='Date the facility was approved or rejected', null=True),
        ),
    ]
