# Generated by Django 4.2.7 on 2023-12-05 12:03

import common.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_offices', '0002_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoffice',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminoffice',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.subcounty'),
        ),
        migrations.AddField(
            model_name='adminoffice',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
